services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Luxletter\:
    resource: '../Classes/*'

  In2code\Luxletter\Domain\Service\QueueService:
    public: true
